
import java.util.ArrayList;
import javax.swing.DefaultComboBoxModel;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;
import javax.swing.tree.DefaultMutableTreeNode;
import javax.swing.tree.DefaultTreeModel;


public class principal extends javax.swing.JFrame {

    DefaultComboBoxModel dc = new DefaultComboBoxModel();
    
    public principal() {
        
        initComponents();
        defaultAliens();
    }
    
    private void defaultAliens(){
        DefaultComboBoxModel x = (DefaultComboBoxModel) jcb_planetaPrimordial.getModel();
        Planeta p = new Planeta();
        Planeta p2 = new Planeta();
        p.setNombrePlaneta("Jupiter");
        p2.setNombrePlaneta("Marte");
        ArrayList<Alienigena> aliens1 = new ArrayList();
        ArrayList<Alienigena> aliens2 = new ArrayList();
        Alienigena a1 = new Explorador("Juan");
        Alienigena a2 = new Cazador("Susana");
        Alienigena a3 = new Cazador("Pedro");
        Alienigena a4 = new Conquistador("Pepe");
        aliens1.add(a1);
        aliens1.add(a2);
        aliens2.add(a3);
        aliens2.add(a4);
        p.setAlienigenasHabitantes(aliens1);
        p2.setAlienigenasHabitantes(aliens2);
        x.addElement(p);
        x.addElement(p2);
        jcb_planetaPrimordial.setModel(x);
        dc = (DefaultComboBoxModel) jcb_planetaPrimordial.getModel();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        popupMenu1 = new java.awt.PopupMenu();
        mi_editar = new java.awt.MenuItem();
        mi_eliminar = new java.awt.MenuItem();
        mi_imprimir = new java.awt.MenuItem();
        jPanel1 = new javax.swing.JPanel();
        jtp_registro = new javax.swing.JTabbedPane();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jtf_nombrePlaneta = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jtf_nombreRaza = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jcb_planetaPrimordial = new javax.swing.JComboBox<>();
        js_temperatura = new javax.swing.JSpinner();
        jLabel9 = new javax.swing.JLabel();
        js_tamanio = new javax.swing.JSpinner();
        jcb_agua = new javax.swing.JCheckBox();
        jb_registrarRaza = new javax.swing.JButton();
        jb_registrarPlaneta = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jtf_nombrePlaneta1 = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jcb_planetaPrimordial1 = new javax.swing.JComboBox<>();
        jcb_razaExp = new javax.swing.JComboBox<>();
        jLabel13 = new javax.swing.JLabel();
        jb_registrarRaza1 = new javax.swing.JButton();
        js_temperatura1 = new javax.swing.JSpinner();
        jScrollPane1 = new javax.swing.JScrollPane();
        jl_listaPlanetasExplorador = new javax.swing.JList<>();
        jb_aniadirListaExplorador = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        jl_planetasExplorador = new javax.swing.JList<>();
        jPanel4 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        jPanel7 = new javax.swing.JPanel();
        jcb_arbol = new javax.swing.JComboBox<>();
        jScrollPane2 = new javax.swing.JScrollPane();
        jl_arbol = new javax.swing.JList<>();
        jb_arbol = new javax.swing.JButton();
        jScrollPane4 = new javax.swing.JScrollPane();
        jt_arbol = new javax.swing.JTree();
        jLabel3 = new javax.swing.JLabel();

        popupMenu1.setLabel("popupMenu1");

        mi_editar.setLabel("menuItem1");
        popupMenu1.add(mi_editar);

        mi_eliminar.setLabel("menuItem1");
        popupMenu1.add(mi_eliminar);

        mi_imprimir.setLabel("menuItem1");
        popupMenu1.add(mi_imprimir);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jtp_registro.setBackground(new java.awt.Color(255, 255, 255));
        jtp_registro.setForeground(new java.awt.Color(51, 51, 51));
        jtp_registro.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jtp_registroStateChanged(evt);
            }
        });

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(51, 51, 51));
        jLabel1.setText("Planetas");

        jLabel4.setBackground(new java.awt.Color(255, 255, 255));
        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(51, 51, 51));
        jLabel4.setText("Razas");

        jLabel5.setBackground(new java.awt.Color(255, 255, 255));
        jLabel5.setForeground(new java.awt.Color(51, 51, 51));
        jLabel5.setText("Nombre");

        jtf_nombrePlaneta.setBackground(new java.awt.Color(255, 255, 255));
        jtf_nombrePlaneta.setForeground(new java.awt.Color(51, 51, 51));

        jLabel6.setBackground(new java.awt.Color(255, 255, 255));
        jLabel6.setForeground(new java.awt.Color(51, 51, 51));
        jLabel6.setText("Nombre");

        jtf_nombreRaza.setBackground(new java.awt.Color(255, 255, 255));
        jtf_nombreRaza.setForeground(new java.awt.Color(51, 51, 51));

        jLabel7.setBackground(new java.awt.Color(255, 255, 255));
        jLabel7.setForeground(new java.awt.Color(51, 51, 51));
        jLabel7.setText("Planeta Primordial");

        jLabel8.setBackground(new java.awt.Color(255, 255, 255));
        jLabel8.setForeground(new java.awt.Color(51, 51, 51));
        jLabel8.setText("Temperatura");

        jcb_planetaPrimordial.setBackground(new java.awt.Color(255, 255, 255));
        jcb_planetaPrimordial.setForeground(new java.awt.Color(51, 51, 51));

        js_temperatura.setModel(new javax.swing.SpinnerNumberModel(0, 0, 100, 1));

        jLabel9.setBackground(new java.awt.Color(255, 255, 255));
        jLabel9.setForeground(new java.awt.Color(51, 51, 51));
        jLabel9.setText("Tamaño");

        js_tamanio.setModel(new javax.swing.SpinnerNumberModel(0, 0, null, 1));

        jcb_agua.setBackground(new java.awt.Color(255, 255, 255));
        jcb_agua.setForeground(new java.awt.Color(51, 51, 51));
        jcb_agua.setText("Agua");

        jb_registrarRaza.setBackground(new java.awt.Color(255, 255, 255));
        jb_registrarRaza.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jb_registrarRaza.setForeground(new java.awt.Color(51, 51, 51));
        jb_registrarRaza.setText("Registrar Raza");
        jb_registrarRaza.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jb_registrarRazaMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jb_registrarRazaMouseEntered(evt);
            }
        });

        jb_registrarPlaneta.setBackground(new java.awt.Color(255, 255, 255));
        jb_registrarPlaneta.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jb_registrarPlaneta.setForeground(new java.awt.Color(51, 51, 51));
        jb_registrarPlaneta.setText("Registrar Planeta");
        jb_registrarPlaneta.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jb_registrarPlanetaMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(49, 49, 49)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jb_registrarPlaneta, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jcb_agua))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jLabel1)
                                .addComponent(jLabel5)
                                .addComponent(jtf_nombrePlaneta)
                                .addComponent(jLabel8)
                                .addComponent(js_temperatura, javax.swing.GroupLayout.DEFAULT_SIZE, 174, Short.MAX_VALUE))
                            .addComponent(jLabel9)
                            .addComponent(js_tamanio, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 158, Short.MAX_VALUE)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jLabel6)
                                .addComponent(jtf_nombreRaza)
                                .addComponent(jLabel4)
                                .addComponent(jLabel7)
                                .addComponent(jcb_planetaPrimordial, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jb_registrarRaza, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(207, 207, 207))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jLabel7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtf_nombrePlaneta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jcb_planetaPrimordial, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jLabel8))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtf_nombreRaza, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(js_temperatura, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel9)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(js_tamanio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jb_registrarRaza, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jcb_agua)
                .addGap(18, 18, 18)
                .addComponent(jb_registrarPlaneta, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(117, Short.MAX_VALUE))
        );

        jtp_registro.addTab("Planetas y Razas", jPanel2);

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));

        jLabel10.setBackground(new java.awt.Color(255, 255, 255));
        jLabel10.setForeground(new java.awt.Color(51, 51, 51));
        jLabel10.setText("Nombre");

        jtf_nombrePlaneta1.setBackground(new java.awt.Color(255, 255, 255));
        jtf_nombrePlaneta1.setForeground(new java.awt.Color(51, 51, 51));

        jLabel11.setBackground(new java.awt.Color(255, 255, 255));
        jLabel11.setForeground(new java.awt.Color(51, 51, 51));
        jLabel11.setText("Edad");

        jLabel12.setBackground(new java.awt.Color(255, 255, 255));
        jLabel12.setForeground(new java.awt.Color(51, 51, 51));
        jLabel12.setText("Raza");

        jcb_planetaPrimordial1.setBackground(new java.awt.Color(255, 255, 255));
        jcb_planetaPrimordial1.setForeground(new java.awt.Color(51, 51, 51));

        jcb_razaExp.setBackground(new java.awt.Color(255, 255, 255));
        jcb_razaExp.setForeground(new java.awt.Color(51, 51, 51));

        jLabel13.setBackground(new java.awt.Color(255, 255, 255));
        jLabel13.setForeground(new java.awt.Color(51, 51, 51));
        jLabel13.setText("Planeta Favorito");

        jb_registrarRaza1.setBackground(new java.awt.Color(255, 255, 255));
        jb_registrarRaza1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jb_registrarRaza1.setForeground(new java.awt.Color(51, 51, 51));
        jb_registrarRaza1.setText("Registrar Raza");
        jb_registrarRaza1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jb_registrarRaza1MouseClicked(evt);
            }
        });

        js_temperatura1.setModel(new javax.swing.SpinnerNumberModel(0, 0, 100, 1));

        jl_listaPlanetasExplorador.setModel(new DefaultListModel());
        jScrollPane1.setViewportView(jl_listaPlanetasExplorador);

        jb_aniadirListaExplorador.setBackground(new java.awt.Color(255, 255, 255));
        jb_aniadirListaExplorador.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jb_aniadirListaExplorador.setForeground(new java.awt.Color(51, 51, 51));
        jb_aniadirListaExplorador.setText("Añadir a su Lista");
        jb_aniadirListaExplorador.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jb_aniadirListaExploradorMouseClicked(evt);
            }
        });

        jl_planetasExplorador.setModel(new DefaultListModel());
        jScrollPane3.setViewportView(jl_planetasExplorador);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(js_temperatura1, javax.swing.GroupLayout.DEFAULT_SIZE, 181, Short.MAX_VALUE)
                    .addComponent(jtf_nombrePlaneta1)
                    .addComponent(jLabel11)
                    .addComponent(jLabel10))
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 44, Short.MAX_VALUE)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jcb_razaExp, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel12))
                        .addGap(36, 36, 36)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel13)
                            .addComponent(jcb_planetaPrimordial1, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jb_registrarRaza1, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(114, 114, 114))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jb_aniadirListaExplorador, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel3Layout.createSequentialGroup()
                    .addGap(49, 49, 49)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addGap(532, 532, 532)))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(jLabel12)
                    .addComponent(jLabel13))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtf_nombrePlaneta1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jcb_planetaPrimordial1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jcb_razaExp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(jb_registrarRaza1, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(js_temperatura1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(76, 76, 76)
                        .addComponent(jb_aniadirListaExplorador, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(57, 57, 57)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(103, Short.MAX_VALUE))
            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                    .addContainerGap(192, Short.MAX_VALUE)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(104, 104, 104)))
        );

        jtp_registro.addTab("Explorador", jPanel3);

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 762, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 463, Short.MAX_VALUE)
        );

        jtp_registro.addTab("Cazador", jPanel4);

        jPanel5.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 762, Short.MAX_VALUE)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 463, Short.MAX_VALUE)
        );

        jtp_registro.addTab("Conquistador", jPanel5);

        jPanel6.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 762, Short.MAX_VALUE)
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 463, Short.MAX_VALUE)
        );

        jtp_registro.addTab("Abduzcan", jPanel6);

        jPanel7.setBackground(new java.awt.Color(255, 255, 255));

        jcb_arbol.setBackground(new java.awt.Color(255, 255, 255));
        jcb_arbol.setForeground(new java.awt.Color(51, 51, 51));
        jcb_arbol.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jcb_arbolItemStateChanged(evt);
            }
        });

        jl_arbol.setModel(new DefaultListModel());
        jScrollPane2.setViewportView(jl_arbol);

        jb_arbol.setText(">");
        jb_arbol.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jb_arbolMouseClicked(evt);
            }
        });

        javax.swing.tree.DefaultMutableTreeNode treeNode1 = new javax.swing.tree.DefaultMutableTreeNode("root");
        jt_arbol.setModel(new javax.swing.tree.DefaultTreeModel(treeNode1));
        jScrollPane4.setViewportView(jt_arbol);

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jcb_arbol, 0, 167, Short.MAX_VALUE)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jb_arbol, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(381, Short.MAX_VALUE))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 433, Short.MAX_VALUE)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addComponent(jcb_arbol, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel7Layout.createSequentialGroup()
                                .addGap(148, 148, 148)
                                .addComponent(jb_arbol, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(jPanel7Layout.createSequentialGroup()
                                .addGap(12, 12, 12)
                                .addComponent(jScrollPane2)))))
                .addContainerGap())
        );

        jtp_registro.addTab("Arbol", jPanel7);

        jLabel3.setBackground(new java.awt.Color(255, 255, 255));
        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(51, 51, 51));
        jLabel3.setText("Registro de Alienigenas");
        jLabel3.setOpaque(true);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(jtp_registro, javax.swing.GroupLayout.PREFERRED_SIZE, 762, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(31, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel3)
                .addGap(18, 18, 18)
                .addComponent(jtp_registro, javax.swing.GroupLayout.PREFERRED_SIZE, 496, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(31, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jb_registrarPlanetaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jb_registrarPlanetaMouseClicked
        try{            
            boolean band = false;
            dc = (DefaultComboBoxModel) jcb_planetaPrimordial.getModel();
            for(int i = 0; i < dc.getSize(); i++){
                if(((Planeta) dc.getElementAt(i)).getNombrePlaneta().equalsIgnoreCase(jtf_nombrePlaneta.getText())){
                    band = true;
                    break;
                }
            }    
            if(jtf_nombrePlaneta.getText().equals("")){
                band = true;
            }
           
            if(band == false){
                Planeta p = new Planeta();
                p.setNombrePlaneta(jtf_nombrePlaneta.getText());
                p.setHayAgua(jcb_agua.isSelected());
                p.setTamanio((int) js_tamanio.getValue());
                p.setTemperatura((int) js_temperatura.getValue());
                
                dc.addElement(p);
                jcb_planetaPrimordial.setModel(dc);
                JOptionPane.showMessageDialog(this, "El planeta se agregó con éxito");
                
            }else{
                JOptionPane.showMessageDialog(this, "El planeta ya existe o no tiene nombre.");
            }
            
            jtf_nombrePlaneta.setText("");
            jcb_agua.setSelected(false);
            js_tamanio.setValue(0);
            js_temperatura.setValue(0);
        }catch(Exception e){
            JOptionPane.showMessageDialog(this, "Error, no se pudo agregar el planeta!");
        }
    }//GEN-LAST:event_jb_registrarPlanetaMouseClicked

    private void jb_registrarRazaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jb_registrarRazaMouseClicked
        try{            
            boolean band = false;
            DefaultComboBoxModel x = (DefaultComboBoxModel) jcb_razaExp.getModel();
            for(int i = 0; i < x.getSize(); i++){
                Raza r = (Raza) x.getElementAt(i);
                if(r.getNombreRaza().equalsIgnoreCase(jtf_nombreRaza.getText())){
                    band = true;
                    break;
                }
            }    
            if(jtf_nombreRaza.getText().equals("")){
                band = true;
            }
           
            if(band == false){                
                if(jcb_planetaPrimordial.getSelectedIndex() >= 0){            
                    x.addElement(new Raza( (Planeta) jcb_planetaPrimordial.getSelectedItem(), jtf_nombreRaza.getText()));
                }
                jcb_razaExp.setModel(x);
                JOptionPane.showMessageDialog(this, "Se agregó la raza correctamente.");

            }else{
                JOptionPane.showMessageDialog(this, "La raza ya existe o no tiene nombre.");
            }            
            
            jcb_planetaPrimordial.setSelectedIndex(0);
            jtf_nombreRaza.setText("");
        }catch(Exception e){
            JOptionPane.showMessageDialog(this, "Error, no se pudo agregar la raza!");
        }
    }//GEN-LAST:event_jb_registrarRazaMouseClicked

    private void jb_registrarRaza1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jb_registrarRaza1MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jb_registrarRaza1MouseClicked

    private void jb_aniadirListaExploradorMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jb_aniadirListaExploradorMouseClicked
        
        DefaultListModel m = (DefaultListModel) jl_listaPlanetasExplorador.getModel();
        DefaultListModel j = (DefaultListModel) jl_planetasExplorador.getModel();
        boolean existe = false;
        Planeta p = new Planeta();
        for (int i = 0; i < m.getSize(); i++) {
            p = (Planeta)j.getElementAt(jl_planetasExplorador.getSelectedIndex());
            if( (Planeta)m.getElementAt(i) == p){
                existe = true;
            }
        }
        if(!existe)
            m.addElement(p);
    }//GEN-LAST:event_jb_aniadirListaExploradorMouseClicked

    private void jtp_registroStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jtp_registroStateChanged
        ArrayList<Object> modelo = new ArrayList();
        for (int i = 0; i < dc.getSize(); i++) {
                modelo.add(dc.getElementAt(i));
            }           
        try{
            DefaultListModel j = (DefaultListModel) jl_planetasExplorador.getModel();
            jcb_arbol.setModel(dc);            
            for (int i = 0; i < dc.getSize(); i++) {
                j.addElement(modelo.get(i));                
            } 
        }catch(Exception e){
            
        }       
    }//GEN-LAST:event_jtp_registroStateChanged

    private void jb_registrarRazaMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jb_registrarRazaMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_jb_registrarRazaMouseEntered

    private void jcb_arbolItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jcb_arbolItemStateChanged
        jl_arbol.setModel(new DefaultListModel());
        if(jcb_arbol.getSelectedIndex() >= 0){
            Planeta p = (Planeta) jcb_arbol.getSelectedItem();
            DefaultListModel j = (DefaultListModel) jl_arbol.getModel();
            for (Alienigena a : p.getAlienigenasHabitantes()) {
                j.addElement(a);
            }
            jl_arbol.setModel(j);
        }
    }//GEN-LAST:event_jcb_arbolItemStateChanged

    private void jb_arbolMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jb_arbolMouseClicked
        if(jl_arbol.getSelectedIndex() >= 0){
            DefaultTreeModel t = (DefaultTreeModel) jt_arbol.getModel();
            DefaultMutableTreeNode root = (DefaultMutableTreeNode) t.getRoot();
            DefaultMutableTreeNode nodoAlien = new DefaultMutableTreeNode();
            DefaultMutableTreeNode nodoPlaneta = new DefaultMutableTreeNode();
            DefaultMutableTreeNode nodoTipo = new DefaultMutableTreeNode();
            DefaultListModel j = (DefaultListModel) jl_arbol.getModel();
            Alienigena a = (Alienigena) j.getElementAt(jl_arbol.getSelectedIndex());
            
            ArrayList<Planeta> modelo = new ArrayList();
            for (int i = 0; i < dc.getSize(); i++) {
                modelo.add((Planeta)dc.getElementAt(i));
            }
            
            for (Planeta p : modelo) {
                for (Alienigena al : p.getAlienigenasHabitantes()) {
                    if(al == a){                        
                        nodoPlaneta = new DefaultMutableTreeNode(p);
                        nodoAlien = new DefaultMutableTreeNode(a);
                    }
                    
                    if(al instanceof Explorador){
                        nodoTipo = new DefaultMutableTreeNode("Explorador");
                    }else if(al instanceof Conquistador){
                        nodoTipo = new DefaultMutableTreeNode("Conquistador");
                    }else if(al instanceof Cazador){
                        nodoTipo = new DefaultMutableTreeNode("Cazador");
                    }else if(al instanceof Abduzcan){
                        nodoTipo = new DefaultMutableTreeNode("Abduzcan");
                    }
                }
            }    
           
            nodoTipo.add(nodoAlien);
            nodoPlaneta.add(nodoTipo);
            root.add(nodoPlaneta);
            t.reload();
        }
    }//GEN-LAST:event_jb_arbolMouseClicked

    
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new principal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JButton jb_aniadirListaExplorador;
    private javax.swing.JButton jb_arbol;
    private javax.swing.JButton jb_registrarPlaneta;
    private javax.swing.JButton jb_registrarRaza;
    private javax.swing.JButton jb_registrarRaza1;
    private javax.swing.JCheckBox jcb_agua;
    private javax.swing.JComboBox<String> jcb_arbol;
    private javax.swing.JComboBox<String> jcb_planetaPrimordial;
    private javax.swing.JComboBox<String> jcb_planetaPrimordial1;
    private javax.swing.JComboBox<String> jcb_razaExp;
    private javax.swing.JList<String> jl_arbol;
    private javax.swing.JList<String> jl_listaPlanetasExplorador;
    private javax.swing.JList<String> jl_planetasExplorador;
    private javax.swing.JSpinner js_tamanio;
    private javax.swing.JSpinner js_temperatura;
    private javax.swing.JSpinner js_temperatura1;
    private javax.swing.JTree jt_arbol;
    private javax.swing.JTextField jtf_nombrePlaneta;
    private javax.swing.JTextField jtf_nombrePlaneta1;
    private javax.swing.JTextField jtf_nombreRaza;
    private javax.swing.JTabbedPane jtp_registro;
    private java.awt.MenuItem mi_editar;
    private java.awt.MenuItem mi_eliminar;
    private java.awt.MenuItem mi_imprimir;
    private java.awt.PopupMenu popupMenu1;
    // End of variables declaration//GEN-END:variables
}
